name: "Update static website"

on:
  push:
    branches:
      - development

  pull_request:
    branches:
      - development

  workflow_dispatch:

permissions:
  contents: write # need write access to this repo to update static website

defaults:
  run:
    shell: bash
    # working-directory: ${{ github.workspace }}

jobs:
  update-static-website:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: pynb-dag-runner/pynb-dag-runner
          path: pynb-dag-runner-repo
          #ref: revised_artifact_format
          persist-credentials: true

      - name: "Install Taskfile"
        working-directory: ${{ github.workspace }}
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b .
          ${{ github.workspace }}/task --version

      - name: "Build Docker file"
        working-directory: ${{ github.workspace }}/pynb-dag-runner-repo/otel_output_parser
        run: |
          ${{ github.workspace }}/task docker:build

      - name: "Fetch all artefacts into directory tree"
        working-directory: ${{ github.workspace }}
        run: |
          # GITHUB_REPOSITORY has format owner/repo-name.
          docker run -t --rm \
            --volume ${{ github.workspace }}:/github_workspace \
            -e GITHUB_TOKEN \
            -e GITHUB_REPOSITORY \
            ci-tools-image "(\
              cd /github_workspace/pynb-dag-runner-repo/otel_output_parser/workspace; \
              pip install -e . ; \
              static_builder \
                --github_repository $GITHUB_REPOSITORY \
                --output_dir /github_workspace/www-root/pipeline-artifacts/ \
                --output_static_mlflow_data /github_workspace/ui_static_data.js; \
            )"
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

      ###
      ### Make static ML Flow
      ###
      - uses: actions/checkout@v3
        with:
          repository: pynb-dag-runner/mlflow
          persist-credentials: true
          path: mlflow-repo
          # replace below with feature branch of `mlflow` repo for testing new
          # UI features using logs from this repo
          ref: uiupdates_2

      # export static ui data (for easier offline debugging)
      - name: "Store ui_static_data.js with data for UI"
        uses: actions/upload-artifact@v2
        with:
          name: ui-static-data
          path: |
              ${{ github.workspace }}/ui_static_data.js
          if-no-files-found: error
          retention-days: 5

      - name: "Build static ML Flow"
        working-directory: ${{ github.workspace }}/mlflow-repo/mlflow/server/js
        run: |
          # copy static pipeline-task-run into ui-source directory
          cp ${{ github.workspace }}/ui_static_data.js \
             ./src/experiment-tracking/static-data/StaticData.js

          make docker-build-image-for-build-static-ui
          make docker-build-static-ui
          cp -r build/. ${{ github.workspace }}/www-root

      ###
      ### Deploy
      ###
      - name: "Push www-root content to repo gh-pages branch"
        working-directory: ${{ github.workspace }}/www-root
        run: |
          # Github pages does not allow directory listing, add files in root
          # for troubleshooting
          find . > list_all_files.txt
          du -hs * > disk_usage.txt

          git init
          git checkout -b gh-pages

          git add -A

          git config --local user.email "gh-automation-bot@github.com"
          git config --local user.name "GitHub Action Bot"
          git commit -m "update"

          git push --force \
            https://my_token_user:${{ secrets.github_token }}@github.com/${GITHUB_REPOSITORY}.git \
            gh-pages:gh-pages
